# Generated by Django 3.2.7 on 2022-04-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issuer',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='issuer',
            new_name='participant',
        ),
    ]
