# Generated by Django 3.2.7 on 2022-05-02 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220502_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='topic',
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topic'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
